Repository graphops/poi-radio, pull requests merged in 2023-05, with the labels that each got.

#119 refactor: move config parsing to Radio
  Cargo.lock
  Cargo.toml
  integration-tests/src/main.rs
  integration-tests/src/setup/test_radio.rs
  src/config.rs
  src/lib.rs
  src/main.rs
Labels: refactor

#122 docs: update release process and script
  .github/dependabot.yml
  CHANGELOG.md
  Cargo.toml
  contributing.md
  pull_request_template.md
  scripts/release.sh
Labels: documentation

#123 refactor: gossip poi refactoring and add benches
  Cargo.lock
  Cargo.toml
  benches/attestations.rs
  benches/gossips.rs
  src/attestation/mod.rs
  src/lib.rs
  src/main.rs
  src/operation.rs
Labels: refactor

#128 fix radio name constant in main
  integration-tests/src/main.rs
  integration-tests/src/setup/test_radio.rs
  src/main.rs
Labels: bug

#127 chore: release v0.1.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  scripts/release.sh
Labels: chore

#129 release v0.1.3
  .github/dependabot.yml
  .gitignore
  .vscode/launch.json
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Dockerfile
  benches/attestations.rs
  benches/gossips.rs
  contributing.md
  e2e-tests.docker-compose.yml
  integration-tests/src/main.rs
  integration-tests/src/setup/test_radio.rs
  integration-tests/src/utils.rs
  pull_request_template.md
  run-e2e-tests.sh
  scripts/release.sh
  src/attestation/mod.rs
  src/config.rs
  src/lib.rs
  src/main.rs
  src/operation.rs
  src/server/mod.rs
  src/server/model/mod.rs
Labels: chore

#130 disable unsubscribe and use timeout
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/operation.rs
Labels: enhancement

#138 chore: update dependencies without conflicts
  Cargo.lock
  Cargo.toml
Labels: chore

#140 Attestation result ratio str query
  src/attestation/mod.rs
  src/main.rs
  src/server/model/mod.rs
Labels: enhancement

#144 Test trigger and docs
  .github/workflows/main.yml
  README.md
Labels: chore

#147 chore: remove e2e test suite from repo
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  README.md
  benches/gossips.rs
  e2e-tests.Dockerfile
  e2e-tests.docker-compose.yml
  integration-tests/.cargo/config.toml
  integration-tests/Cargo.toml
  integration-tests/src/checks/invalid_messages.rs
  integration-tests/src/checks/invalid_sender.rs
  integration-tests/src/checks/mod.rs
  integration-tests/src/checks/poi_divergence_local.rs
  integration-tests/src/checks/poi_divergence_remote.rs
  integration-tests/src/checks/simple_tests.rs
  integration-tests/src/main.rs
  integration-tests/src/setup/basic.rs
  integration-tests/src/setup/constants.rs
  integration-tests/src/setup/divergent.rs
  integration-tests/src/setup/invalid_block_hash.rs
  integration-tests/src/setup/invalid_nonce.rs
  integration-tests/src/setup/invalid_payload.rs
  integration-tests/src/setup/mod.rs
  integration-tests/src/setup/test_radio.rs
  integration-tests/src/utils.rs
  run-e2e-tests.sh
  src/config.rs
Labels: chore

#141 State persistence
  Cargo.toml
  benches/gossips.rs
  src/attestation/mod.rs
  src/config.rs
  src/lib.rs
  src/main.rs
  src/operation.rs
  src/state.rs
Labels: enhancement

#146 Configurable logger formats
  benches/gossips.rs
  src/attestation/mod.rs
  src/config.rs
  src/lib.rs
  src/main.rs
  src/metrics/mod.rs
  src/operation.rs
  src/server/mod.rs
  src/server/model/mod.rs
  src/state.rs
Labels: enhancement

#158 refactor: update logging level
  benches/gossips.rs
  src/operation.rs
Labels: refactor

#163 chore: release v0.3.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: chore

#167 feat: add telegram notifications
  Cargo.lock
  Cargo.toml
  benches/gossips.rs
  src/attestation/mod.rs
  src/config.rs
  src/lib.rs
  src/main.rs
  src/notifier.rs
Labels: enhancement, rust

#171 Add RadioOperator struct and refactor global variables
  .gitignore
  Cargo.lock
  Cargo.toml
  benches/attestations.rs
  benches/gossips.rs
  src/config.rs
  src/graphql/mod.rs
  src/lib.rs
  src/main.rs
  src/operation.rs
  src/operator/attestation.rs
  src/operator/callbook.rs
  src/operator/mod.rs
  src/operator/notifier.rs
  src/operator/operation.rs
  src/server/mod.rs
  src/server/model/mod.rs
  src/server/routes/mod.rs
  src/state.rs
Labels: refactor

#173 refactor: remove 'v' prefix from release tag
  .github/workflows/docker.yml
  scripts/release.sh
Labels: bug, refactor
