Repository graphops/poi-radio, pull requests merged in 2023-04, with the labels that each got.

#87 fix: check for null node
  Cargo.toml
  src/lib.rs
Labels: bug

#92 Expose API endpoint
  Cargo.toml
  src/attestation/mod.rs
  src/lib.rs
  src/main.rs
  src/server/mod.rs
  src/server/model/mod.rs
  src/server/observability/mod.rs
  src/server/routes/mod.rs
Labels: enhancement

#94 feat: add Grafana dashboard config
  poi-radio-grafana.json
Labels: enhancement

#90 feat: move integration tests to main repo
  .github/workflows/main.yml
  .gitignore
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  e2e-tests.Dockerfile
  e2e-tests.docker-compose.yml
  integration-tests/.cargo/config.toml
  integration-tests/Cargo.toml
  integration-tests/src/checks/invalid_messages.rs
  integration-tests/src/checks/invalid_sender.rs
  integration-tests/src/checks/mod.rs
  integration-tests/src/checks/poi_divergence_local.rs
  integration-tests/src/checks/poi_divergence_remote.rs
  integration-tests/src/checks/simple_tests.rs
  integration-tests/src/main.rs
  integration-tests/src/setup/basic.rs
  integration-tests/src/setup/constants.rs
  integration-tests/src/setup/divergent.rs
  integration-tests/src/setup/invalid_block_hash.rs
  integration-tests/src/setup/invalid_nonce.rs
  integration-tests/src/setup/invalid_payload.rs
  integration-tests/src/setup/mod.rs
  integration-tests/src/setup/test_radio.rs
  integration-tests/src/utils.rs
  run-e2e-tests.sh
  run-tests.sh
  src/attestation/mod.rs
  src/graphql/query_block_hash_from_number.graphql
  src/lib.rs
Labels: rust

#104 fix: remove api metrics path
  src/server/mod.rs
  src/server/model/mod.rs
  src/server/observability/mod.rs
Labels: bug

#105 Release v0.1.0
  .auto-changelog
  .github/workflows/docker.yml
  .github/workflows/main.yml
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Dockerfile
  contributing.md
  e2e-tests.Dockerfile
  e2e-tests.docker-compose.yml
  integration-tests/.cargo/config.toml
  integration-tests/Cargo.toml
  integration-tests/src/checks/invalid_messages.rs
  integration-tests/src/checks/invalid_sender.rs
  integration-tests/src/checks/mod.rs
  integration-tests/src/checks/poi_divergence_local.rs
  integration-tests/src/checks/poi_divergence_remote.rs
  integration-tests/src/checks/simple_tests.rs
  integration-tests/src/main.rs
  integration-tests/src/setup/basic.rs
  integration-tests/src/setup/constants.rs
  integration-tests/src/setup/divergent.rs
  integration-tests/src/setup/invalid_block_hash.rs
  integration-tests/src/setup/invalid_nonce.rs
  integration-tests/src/setup/invalid_payload.rs
  integration-tests/src/setup/mod.rs
  integration-tests/src/setup/test_radio.rs
  integration-tests/src/utils.rs
  poi-radio-grafana.json
  run-e2e-tests.sh
  run-tests.sh
  scripts/release.sh
  src/attestation/mod.rs
  src/graphql/query_block_hash_from_number.graphql
  src/lib.rs
  src/server/mod.rs
  src/server/model/mod.rs
  src/server/observability/mod.rs
Labels: chore

#111 fix: return empty vec if indexer_allocations function fails
  pull_request_template.md
  src/lib.rs
Labels: bug

#95 Comparison results by graphql query
  .gitignore
  Cargo.toml
  e2e-tests.docker-compose.yml
  integration-tests/src/main.rs
  integration-tests/src/setup/test_radio.rs
  integration-tests/src/utils.rs
  run-e2e-tests.sh
  src/attestation/mod.rs
  src/lib.rs
  src/main.rs
  src/server/mod.rs
  src/server/model/mod.rs
Labels: enhancement
