Repository graphops/poi-radio, pull requests merged in 2023-06, with the labels that each got.

#176 feat: add e2e tests
  .github/workflows/main.yml
  .gitignore
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  Dockerfile
  poi-radio/Cargo.toml
  poi-radio/benches/attestations.rs
  poi-radio/benches/gossips.rs
  poi-radio/src/config.rs
  poi-radio/src/graphql/mod.rs
  poi-radio/src/graphql/query_block_hash_from_number.graphql
  poi-radio/src/graphql/query_indexing_statuses.graphql
  poi-radio/src/graphql/query_proof_of_indexing.graphql
  poi-radio/src/graphql/schema_graph_node.graphql
  poi-radio/src/lib.rs
  poi-radio/src/main.rs
  poi-radio/src/metrics/mod.rs
  poi-radio/src/operator/attestation.rs
  poi-radio/src/operator/callbook.rs
  poi-radio/src/operator/mod.rs
  poi-radio/src/operator/notifier.rs
  poi-radio/src/operator/operation.rs
  poi-radio/src/server/mod.rs
  poi-radio/src/server/model/mod.rs
  poi-radio/src/server/routes/mod.rs
  poi-radio/src/state.rs
  scripts/release.sh
  test-runner/Cargo.toml
  test-runner/src/main.rs
  test-sender/Cargo.toml
  test-sender/src/main.rs
  test-utils/Cargo.toml
  test-utils/src/config.rs
  test-utils/src/lib.rs
  test-utils/src/mock_server.rs
Labels: enhancement, rust

#182 fix: server context types
  Cargo.lock
  poi-radio/Cargo.toml
  poi-radio/benches/attestations.rs
  poi-radio/src/operator/attestation.rs
  poi-radio/src/operator/operation.rs
  poi-radio/src/server/mod.rs
  poi-radio/src/server/model/mod.rs
Labels: bug

#186 fix: remove double Arc Mutex from state types
  poi-radio/src/config.rs
  poi-radio/src/lib.rs
  poi-radio/src/main.rs
  poi-radio/src/operator/attestation.rs
  poi-radio/src/operator/mod.rs
  poi-radio/src/operator/operation.rs
  poi-radio/src/server/mod.rs
  poi-radio/src/server/model/mod.rs
  poi-radio/src/state.rs
  test-runner/src/main.rs
Labels: bug

#189 chore: update sdk version
  Cargo.lock
  poi-radio/Cargo.toml
  poi-radio/src/config.rs
Labels: chore
